spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true
  datasource:
    url: jdbc:mariadb://rathgeb.at:3306/d03e1108
    username: d03e1108
    password: HTLSTEYR

